plugins:
  plugin_name:
    executor: host_agent
    source: https://codeload.github.com/cloudify-cosmo/cloudify-filebeat-plugin/zip/master
    package_name: cloudify-filebeat-plugin
    package_version: 0.1